
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class actAction
{

    public int ActionId { get; set; }

    public Nullable<int> ActionType { get; set; }

    public Nullable<int> DisciplineId { get; set; }

    public Nullable<int> ActionPriority { get; set; }

    public string ActionDescription { get; set; }

    public string ActionCause { get; set; }

    public string Actions { get; set; }

    public Nullable<int> ActionStatus { get; set; }

    public Nullable<System.DateTime> ActionTargetDate { get; set; }

    public Nullable<int> ActionCreatedBy { get; set; }

    public Nullable<System.DateTime> ActionCreatedOn { get; set; }

    public Nullable<int> ActionModifiedBy { get; set; }

    public Nullable<System.DateTime> ActionModifiedOn { get; set; }

    public Nullable<System.DateTime> ActionCompletionDate { get; set; }

    public Nullable<bool> isPrivate { get; set; }

    public Nullable<bool> isDeleted { get; set; }

    public Nullable<int> ProjectId { get; set; }



    public virtual tblDiscipline tblDiscipline { get; set; }

}

}
