
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class C06ConsSummary
{

    public int EntActId { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<double> BudgQty { get; set; }

    public string ActivityName { get; set; }

    public string ActUnit { get; set; }

    public Nullable<double> ActWtg { get; set; }

    public Nullable<double> ReviseQty { get; set; }

    public Nullable<double> ComplQty { get; set; }

    public Nullable<System.DateTime> Expr1 { get; set; }

    public Nullable<int> ConsActId { get; set; }

    public string ActivityGroup { get; set; }

    public Nullable<double> TotalWtg { get; set; }

    public Nullable<double> CompletedWtg { get; set; }

    public string ActivityCode { get; set; }

}

}
