
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ConstructionActivityView
{

    public int EntActId { get; set; }

    public Nullable<int> ActGId { get; set; }

    public int EntityID { get; set; }

    public string EntityCode { get; set; }

    public string EntityName { get; set; }

    public string ActivityCode { get; set; }

    public string ActivityName { get; set; }

    public string ActUnit { get; set; }

    public Nullable<decimal> BudgQty { get; set; }

    public Nullable<int> PackageId { get; set; }

    public int ConsActId { get; set; }

    public Nullable<double> RevisedQty { get; set; }

    public Nullable<double> CompletedQtyToDate { get; set; }

}

}
