
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class CrossSectionDetailsView
{

    public int AutoID { get; set; }

    public Nullable<int> CsID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> SeqNo { get; set; }

    public string CrossSectionName { get; set; }

    public string ActivityName { get; set; }

    public string StrLayer { get; set; }

    public Nullable<double> MaxLayerThk { get; set; }

    public Nullable<double> BottomWd { get; set; }

    public Nullable<double> Slope { get; set; }

    public Nullable<double> TopWd { get; set; }

    public Nullable<double> TotalThk { get; set; }

}

}
