
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class EnggDwgAttachmentView
{

    public int AttachmentID { get; set; }

    public string Path { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public bool IsDeleted { get; set; }

    public int AutoId { get; set; }

    public Nullable<int> EnggDwgId { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
