
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class EntityTypeWithActGroupView
{

    public string ActivityGroupName { get; set; }

    public int Id { get; set; }

    public string EntityType { get; set; }

    public Nullable<int> ActGId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
