
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class EntityDrawingApprView
{

    public int Id { get; set; }

    public Nullable<int> PackageId { get; set; }

    public int DwgId { get; set; }

    public int ApprGateId { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<int> ActionId { get; set; }

    public Nullable<int> AttachmentId { get; set; }

    public string ActionName { get; set; }

    public string Remark { get; set; }

    public string EntityName { get; set; }

    public string ApprGateName { get; set; }

    public string DwgName { get; set; }

    public Nullable<System.DateTime> ApprStartDate { get; set; }

    public string Revision { get; set; }

    public string DrawingName { get; set; }

    public string FileName { get; set; }

    public string Path { get; set; }

}

}
