
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class InvoiceTotalSumView
{

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public int InvoiceId { get; set; }

}

}
