
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class MaterialWithDisplineView
{

    public int MaterialId { get; set; }

    public string MaterialCode { get; set; }

    public Nullable<int> DispId { get; set; }

    public string MaterialName { get; set; }

    public string MaterialUnit { get; set; }

    public string DispName { get; set; }

}

}
