
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class MilestoneView
{

    public string PackageName { get; set; }

    public int MilestoneId { get; set; }

    public string ProjectName { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string PrimaMileCode { get; set; }

    public string MileName { get; set; }

    public Nullable<System.DateTime> MilePlanDate { get; set; }

    public string ContractMonitor { get; set; }

    public Nullable<bool> ProjCompFlag { get; set; }

    public Nullable<int> Revision { get; set; }

    public Nullable<bool> isActive { get; set; }

    public int ProjectId { get; set; }

    public string PackageCode { get; set; }

}

}
