
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class PackageInvoice
{

    public int PackageId { get; set; }

    public string PackageName { get; set; }

    public int InvoiceId { get; set; }

    public string InvoiceNo { get; set; }

    public Nullable<System.DateTime> InvoiceDate { get; set; }

    public Nullable<decimal> InvoiceAmount { get; set; }

    public Nullable<decimal> CertifiedAmount { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

}

}
