
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class PackageUserDetailsView
{

    public string ProjectName { get; set; }

    public int PackageId { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public string PackageCode { get; set; }

    public string PackageName { get; set; }

    public string PackageShortName { get; set; }

    public string Description { get; set; }

    public string Client { get; set; }

    public string Contractor { get; set; }

    public string PMC { get; set; }

    public string PCPM { get; set; }

    public System.DateTime PackageStart { get; set; }

    public System.DateTime PackageFinish { get; set; }

    public Nullable<System.DateTime> ForecastComplDate { get; set; }

    public Nullable<double> PackageValue { get; set; }

    public string PackageValues { get; set; }

    public Nullable<double> RevisedPackageValue { get; set; }

    public string RevisedPackageValues { get; set; }

    public Nullable<double> CompletedValue { get; set; }

    public string CompletedValues { get; set; }

    public Nullable<double> BalanceValue { get; set; }

    public string BalanceValues { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public double TotalKmLength { get; set; }

    public string PackageCPM { get; set; }

    public string PackageED { get; set; }

    public string TotalKmLengths { get; set; }

    public Nullable<int> Duration { get; set; }

    public Nullable<int> SectionCount { get; set; }

    public Nullable<int> EntityCount { get; set; }

    public Nullable<int> ProcMatDataCount { get; set; }

    public Nullable<int> ProcMatAssignCount { get; set; }

    public Nullable<int> ConsActDataUpdateCount { get; set; }

    public Nullable<int> ConsActivityCount { get; set; }

    public Nullable<int> EnggDrawingCount { get; set; }

    public Nullable<int> InvoiceCount { get; set; }

    public Nullable<int> RFICount { get; set; }

    public Nullable<int> DispUsersCount { get; set; }

    public Nullable<int> RFIUsersCount { get; set; }

    public string Durations { get; set; }

    public Nullable<int> EoTgranted { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsSubscribed { get; set; }

    public Nullable<int> UpdateScore { get; set; }

}

}
