
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class PackageMaterialDetailsView
{

    public int PkgMatId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> MaterialId { get; set; }

    public Nullable<int> DispId { get; set; }

    public decimal RatePerUnit { get; set; }

    public double OriginalQty { get; set; }

    public string MaterialName { get; set; }

    public string MaterialCode { get; set; }

    public string MaterialUnit { get; set; }

    public string DisciplineName { get; set; }

    public string Unit { get; set; }

}

}
