
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class PhysicalProgressView
{

    public string ProjectCode { get; set; }

    public string ProjectName { get; set; }

    public int ProjectId { get; set; }

    public string PhyParaCode { get; set; }

    public string PhyParaName { get; set; }

    public int PhyID { get; set; }

}

}
