
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class PMCReportDetailsView
{

    public int PMCReportId { get; set; }

    public Nullable<int> PRId { get; set; }

    public string PackageName { get; set; }

    public Nullable<int> AttachmentID { get; set; }

    public string Title { get; set; }

    public string Path { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public string PMCReportType { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> ReportingDate { get; set; }

    public string ReportingDates { get; set; }

    public string Remark { get; set; }

    public Nullable<int> PackageId { get; set; }

}

}
