
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class prjBaselineView
{

    public string ProjectCode { get; set; }

    public string ProjectName { get; set; }

    public int ProjectId { get; set; }

    public string BaselineStatus { get; set; }

    public int BaseID { get; set; }

    public Nullable<int> ProjID { get; set; }

    public string BaseRevision { get; set; }

    public Nullable<System.DateTime> BaseSubmissionDate { get; set; }

    public string Remark { get; set; }

    public Nullable<System.DateTime> ResponseDate { get; set; }

}

}
