
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectDetailsView
{

    public int ProjectId { get; set; }

    public string ProjectFullName { get; set; }

    public string ProjectName { get; set; }

    public Nullable<decimal> ProjectLength { get; set; }

    public string ProjectLengths { get; set; }

    public Nullable<decimal> AnticipatedValue { get; set; }

    public string AnticipatedValues { get; set; }

    public Nullable<decimal> ValueTillDate { get; set; }

    public string ValueTillDates { get; set; }

    public string ProjectCode { get; set; }

    public string EDName { get; set; }

    public string PIUName { get; set; }

    public string RailwayCode { get; set; }

    public string ProjectTypeName { get; set; }

    public string PIUCode { get; set; }

    public Nullable<System.DateTime> DateOfTransfer { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

}

}
