
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class rskReview
{

    public int ReviewId { get; set; }

    public Nullable<int> RiskId { get; set; }

    public Nullable<int> ReviewCreator { get; set; }

    public Nullable<System.DateTime> ReviewOn { get; set; }

    public string ReviewNote { get; set; }

    public string ReviewTrend { get; set; }

    public Nullable<System.DateTime> ReviewAcceptDate { get; set; }



    public virtual rskRegister rskRegister { get; set; }

}

}
