
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class rskResponse
{

    public int ResponseId { get; set; }

    public Nullable<int> RiskId { get; set; }

    public string Response { get; set; }

    public Nullable<int> ResponseBy { get; set; }

    public Nullable<System.DateTime> ResponseOn { get; set; }



    public virtual rskRegister rskRegister { get; set; }

}

}
