
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class rskValue
{

    public int Id { get; set; }

    public Nullable<int> Min { get; set; }

    public string Max { get; set; }

    public string Risk { get; set; }

    public string Opportunity { get; set; }

}

}
