
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class SectionView
{

    public string PackageName { get; set; }

    public int SectionID { get; set; }

    public string ProjectName { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string SectionName { get; set; }

    public string SectionCode { get; set; }

    public Nullable<System.DateTime> SectionStart { get; set; }

    public Nullable<System.DateTime> SectionFinish { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<double> Length { get; set; }

    public string SectionLength { get; set; }

    public int ProjectId { get; set; }

    public string PackageCode { get; set; }

}

}
