
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblAudit
{

    public int AuditID { get; set; }

    public string UserName { get; set; }

    public string IPAddress { get; set; }

    public string AreaAccessed { get; set; }

    public Nullable<System.DateTime> TimeAccessed { get; set; }

    public Nullable<int> UserId { get; set; }

    public string FormName { get; set; }

    public string ActionName { get; set; }

}

}
