
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblAppMenu
{

    public int MenuId { get; set; }

    public string MenuName { get; set; }

    public string Description { get; set; }

    public string URL { get; set; }

    public int ParrentId { get; set; }

    public bool IsDeleted { get; set; }

    public string MenuCode { get; set; }

    public string LiTagId { get; set; }

    public string Icon { get; set; }

    public Nullable<int> ParentOrder { get; set; }

    public Nullable<bool> IsRFI { get; set; }

}

}
