
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblAchievement
{

    public int AchID { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> AchSeq { get; set; }

    public string AchDesc { get; set; }

    public Nullable<double> AchQty { get; set; }

    public string AchQtyUnit { get; set; }

    public string Remark { get; set; }

    public Nullable<bool> IsDelete { get; set; }



    public virtual tblMasterProject tblMasterProject { get; set; }

}

}
