
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblAttachment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblAttachment()
    {

        this.tblInvoicePayments = new HashSet<tblInvoicePayment>();

        this.tblPkgMatTransactions = new HashSet<tblPkgMatTransaction>();

        this.tblPMCReportDetails = new HashSet<tblPMCReportDetail>();

    }


    public int AttachmentID { get; set; }

    public string Path { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public string FileSize { get; set; }



    public virtual tblAttachment tblAttachments1 { get; set; }

    public virtual tblAttachment tblAttachment1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblInvoicePayment> tblInvoicePayments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPkgMatTransaction> tblPkgMatTransactions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPMCReportDetail> tblPMCReportDetails { get; set; }

}

}
