
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblActivityGroup
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblActivityGroup()
    {

        this.tblConsActivities = new HashSet<tblConsActivity>();

        this.tblEntityTypes = new HashSet<tblEntityType>();

    }


    public int ActGId { get; set; }

    public string ActivityGroupName { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsActivity> tblConsActivities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEntityType> tblEntityTypes { get; set; }

}

}
