
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblBOQMaster
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblBOQMaster()
    {

        this.tblRFIActivityBOQs = new HashSet<tblRFIActivityBOQ>();

    }


    public int BoqID { get; set; }

    public string BoqCode { get; set; }

    public string BoqName { get; set; }

    public string BoqUnit { get; set; }

    public Nullable<double> BoqRate { get; set; }

    public Nullable<double> BoqQty { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIActivityBOQ> tblRFIActivityBOQs { get; set; }

}

}
