
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsEntActTran
{

    public int Id { get; set; }

    public Nullable<int> EntActId { get; set; }

    public Nullable<System.DateTime> TransDate { get; set; }

    public Nullable<double> RevisedQty { get; set; }

    public Nullable<double> CompletedQty { get; set; }

    public Nullable<System.DateTime> TargetDate { get; set; }

    public string Remark { get; set; }

    public Nullable<int> AttachmentId { get; set; }



    public virtual tblConsEntAct tblConsEntAct { get; set; }

}

}
