
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsEntAct
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblConsEntAct()
    {

        this.tblConsEntActTrans = new HashSet<tblConsEntActTran>();

    }


    public int EntActId { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<int> ConsActId { get; set; }

    public Nullable<double> BudgQty { get; set; }

    public string Unit { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tblConsActivity tblConsActivity { get; set; }

    public virtual tblMasterEntity tblMasterEntity { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsEntActTran> tblConsEntActTrans { get; set; }

}

}
