
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblConsActivity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblConsActivity()
    {

        this.tblConsEntActs = new HashSet<tblConsEntAct>();

        this.tblRFIActivities = new HashSet<tblRFIActivity>();

        this.tblStripPkgActs = new HashSet<tblStripPkgAct>();

    }


    public int ConsActId { get; set; }

    public Nullable<int> ActGId { get; set; }

    public string ActivityGroup { get; set; }

    public string ActivityCode { get; set; }

    public string ActivityName { get; set; }

    public string ActUnit { get; set; }

    public Nullable<double> ActWtg { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<bool> isStripChart { get; set; }

    public Nullable<bool> IsRFI { get; set; }

    public Nullable<bool> KeyFlag { get; set; }



    public virtual tblActivityGroup tblActivityGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsEntAct> tblConsEntActs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIActivity> tblRFIActivities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblStripPkgAct> tblStripPkgActs { get; set; }

}

}
