
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDeletedRecordLog
{

    public int AutoId { get; set; }

    public string TableName { get; set; }

    public Nullable<int> NoOfRecords { get; set; }

    public string DeletedIds { get; set; }

    public Nullable<System.DateTime> DeletedOn { get; set; }

}

}
