
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDroneSurveyDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblDroneSurveyDetail()
    {

        this.tblDroneImageVideos = new HashSet<tblDroneImageVideo>();

    }


    public int DSId { get; set; }

    public int PackageId { get; set; }

    public Nullable<int> SectionID { get; set; }

    public Nullable<int> EntityID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<double> StartChaninage { get; set; }

    public Nullable<double> EndChaninage { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDroneImageVideo> tblDroneImageVideos { get; set; }

    public virtual tblDroneSurveyDetail tblDroneSurveyDetails1 { get; set; }

    public virtual tblDroneSurveyDetail tblDroneSurveyDetail1 { get; set; }

}

}
