
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDataIssue
{

    public int IssueId { get; set; }

    public string DataTicket { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string ShortDescription { get; set; }

    public string Description { get; set; }

    public string Attachment { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<int> StatusId { get; set; }

    public string Remark { get; set; }

}

}
