
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDemo
{

    public int DemoId { get; set; }

    public Nullable<int> PackageID { get; set; }

    public Nullable<System.DateTime> DemoDate { get; set; }

    public Nullable<int> TimeslotID { get; set; }

    public Nullable<int> ModuleId { get; set; }

    public string Name { get; set; }

    public string MobileNo { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> StatusID { get; set; }

}

}
