
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDroneImageVideo
{

    public int FileID { get; set; }

    public int DSId { get; set; }

    public string DFileName { get; set; }

    public Nullable<int> DFileType { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    public virtual tblDroneSurveyDetail tblDroneSurveyDetail { get; set; }

}

}
