
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblDocument
{

    public int DocumentId { get; set; }

    public Nullable<int> UserID { get; set; }

    public string DocumnetType { get; set; }

    public Nullable<System.DateTime> UploadedOn { get; set; }

    public string FileName { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> PackageID { get; set; }

    public string FilePath { get; set; }

}

}
