
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblEnggDwgAttachment
{

    public int AutoId { get; set; }

    public Nullable<int> AttachmentID { get; set; }

    public Nullable<int> EnggDwgId { get; set; }

}

}
