
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblEnggEntDwgAppr
{

    public int Id { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<int> DwgId { get; set; }

    public Nullable<int> AppGateId { get; set; }

    public string Revision { get; set; }

    public Nullable<System.DateTime> ApprStartDate { get; set; }

    public Nullable<System.DateTime> ApprFinsihDate { get; set; }

    public Nullable<int> ActionId { get; set; }

    public string Remark { get; set; }

    public Nullable<int> AttachmentId { get; set; }

    public string DrawingName { get; set; }



    public virtual tblEnggApprGate tblEnggApprGate { get; set; }

    public virtual tblEnggDwgType tblEnggDwgType { get; set; }

    public virtual tblMasterEntity tblMasterEntity { get; set; }

}

}
