
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblIssue
{

    public int Id { get; set; }

    public string IssueRegNo { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string IssueDescription { get; set; }

    public string IssueSubject { get; set; }

    public Nullable<int> DisciplineId { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public string otherLocation { get; set; }

    public Nullable<int> EntityId { get; set; }

    public string Location { get; set; }

    public Nullable<System.DateTime> IssueDate { get; set; }

    public string Attachment { get; set; }

    public string AttachmentPath { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> IssueAddeby { get; set; }

}

}
