
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblInvoice
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblInvoice()
    {

        this.tblInvoicePayments = new HashSet<tblInvoicePayment>();

    }


    public int InvoiceId { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string InvoiceNo { get; set; }

    public Nullable<System.DateTime> InvoiceDate { get; set; }

    public Nullable<decimal> InvoiceAmount { get; set; }

    public Nullable<decimal> CertifiedAmount { get; set; }

    public string Remark { get; set; }

    public Nullable<bool> IsPaid { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tblMasterProject tblMasterProject { get; set; }

    public virtual tblPackage tblPackage { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblInvoicePayment> tblInvoicePayments { get; set; }

}

}
