
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblKPIPlanActual
{

    public int AutoID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> ResourceId { get; set; }

    public Nullable<System.DateTime> DataDate { get; set; }

    public Nullable<decimal> ActualUnit { get; set; }

    public Nullable<decimal> RemainingEarlyUnit { get; set; }

    public Nullable<decimal> RemainingLateUnit { get; set; }



    public virtual tblPackage tblPackage { get; set; }

    public virtual tblResource tblResource { get; set; }

}

}
