
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblMilestoneActual
{

    public int Id { get; set; }

    public Nullable<int> MilestoneId { get; set; }

    public Nullable<System.DateTime> DataDate { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> MileDate { get; set; }

}

}
