
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasterEntity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblMasterEntity()
    {

        this.tblConsEntActs = new HashSet<tblConsEntAct>();

        this.tblEnggEntDwgApprs = new HashSet<tblEnggEntDwgAppr>();

    }


    public int EntityID { get; set; }

    public Nullable<int> SectionID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public string EntityCode { get; set; }

    public string EntityName { get; set; }

    public string EntityType { get; set; }

    public string Lat { get; set; }

    public string Long { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblConsEntAct> tblConsEntActs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEnggEntDwgAppr> tblEnggEntDwgApprs { get; set; }

    public virtual tblMasterProject tblMasterProject { get; set; }

    public virtual tblPackage tblPackage { get; set; }

}

}
