
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblModule
{

    public int ModuleId { get; set; }

    public string ModuleName { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public string Color { get; set; }

}

}
