
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblMaterialDistribution
{

    public int EMDId { get; set; }

    public Nullable<int> PackMatId { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<double> EMOrderedQty { get; set; }

    public Nullable<double> EMDeliveredQty { get; set; }

}

}
