
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasterPIU
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblMasterPIU()
    {

        this.tblMasterProjects = new HashSet<tblMasterProject>();

    }


    public int PIUId { get; set; }

    public int EDId { get; set; }

    public string PIUCode { get; set; }

    public string PIUName { get; set; }

    public Nullable<decimal> Latitute { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<bool> IsDelete { get; set; }



    public virtual tblMasterED tblMasterED { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMasterProject> tblMasterProjects { get; set; }

}

}
