
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblMasterProject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblMasterProject()
    {

        this.tblInvoices = new HashSet<tblInvoice>();

        this.tblMasterEntities = new HashSet<tblMasterEntity>();

        this.tblPackages = new HashSet<tblPackage>();

        this.tblSections = new HashSet<tblSection>();

        this.prjInvDueDates = new HashSet<prjInvDueDate>();

        this.tblAchievements = new HashSet<tblAchievement>();

        this.tblAreaOfConcerns = new HashSet<tblAreaOfConcern>();

        this.tblAreaOfConcerns1 = new HashSet<tblAreaOfConcern>();

        this.tblBaselines = new HashSet<tblBaseline>();

        this.tblcashParamenters = new HashSet<tblcashParamenter>();

        this.tblEOTs = new HashSet<tblEOT>();

        this.tblHscParamenters = new HashSet<tblHscParamenter>();

        this.tblkpiParamenters = new HashSet<tblkpiParamenter>();

        this.tblphyParamenters = new HashSet<tblphyParamenter>();

        this.tblQaqcParamenters = new HashSet<tblQaqcParamenter>();

        this.tblMilestones = new HashSet<tblMilestone>();

    }


    public int ProjectId { get; set; }

    public Nullable<int> EDId { get; set; }

    public Nullable<int> PIUId { get; set; }

    public string ProjectCode { get; set; }

    public string ProjectName { get; set; }

    public string ProjectFullName { get; set; }

    public Nullable<System.DateTime> DateOfTransfer { get; set; }

    public Nullable<decimal> ProjectLength { get; set; }

    public Nullable<int> RailwayId { get; set; }

    public Nullable<int> ProjectTypeId { get; set; }

    public Nullable<decimal> AnticipatedValue { get; set; }

    public Nullable<decimal> ValueTillDate { get; set; }

    public Nullable<bool> IsMonitorFlag { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblInvoice> tblInvoices { get; set; }

    public virtual tblMasterED tblMasterED { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMasterEntity> tblMasterEntities { get; set; }

    public virtual tblMasterPIU tblMasterPIU { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPackage> tblPackages { get; set; }

    public virtual tblMasterRailway tblMasterRailway { get; set; }

    public virtual tblProjectType tblProjectType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSection> tblSections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<prjInvDueDate> prjInvDueDates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAchievement> tblAchievements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAreaOfConcern> tblAreaOfConcerns { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblAreaOfConcern> tblAreaOfConcerns1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBaseline> tblBaselines { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblcashParamenter> tblcashParamenters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEOT> tblEOTs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblHscParamenter> tblHscParamenters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblkpiParamenter> tblkpiParamenters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblphyParamenter> tblphyParamenters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblQaqcParamenter> tblQaqcParamenters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMilestone> tblMilestones { get; set; }

}

}
