
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblNotificationMsg
{

    public int NotificationId { get; set; }

    public Nullable<int> SenderId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public Nullable<int> TblType { get; set; }

    public Nullable<int> ReceiverId { get; set; }

    public Nullable<bool> isDelivered { get; set; }

    public Nullable<System.DateTime> SentOn { get; set; }

    public Nullable<System.DateTime> DeliveredOn { get; set; }

    public string Response { get; set; }

}

}
