
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblNotificationSetting
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public Nullable<bool> IsEmail { get; set; }

    public Nullable<bool> IsSMS { get; set; }

    public Nullable<bool> IsWhatsApp { get; set; }

    public Nullable<bool> IsAppPush { get; set; }

    public Nullable<bool> IsDesktopPush { get; set; }

    public Nullable<bool> IsPopup { get; set; }

}

}
