
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblPkgChngLvl
{

    public int ID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<double> Chainage { get; set; }

    public Nullable<double> OGL { get; set; }

    public Nullable<double> FRL { get; set; }

    public Nullable<double> FormLvl { get; set; }



    public virtual tblPackage tblPackage { get; set; }

}

}
