
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblPMCReportDetail
{

    public int PMCReportId { get; set; }

    public Nullable<int> PRId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> AttachmentID { get; set; }

    public string Title { get; set; }

    public string Remark { get; set; }

    public Nullable<System.DateTime> ReportingDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    public virtual tblAttachment tblAttachment { get; set; }

    public virtual tblPackage tblPackage { get; set; }

    public virtual tblPMCReportType tblPMCReportType { get; set; }

}

}
