
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblPackage
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPackage()
    {

        this.tblCashFlows = new HashSet<tblCashFlow>();

        this.tblInvoices = new HashSet<tblInvoice>();

        this.tblKPIPlanActuals = new HashSet<tblKPIPlanActual>();

        this.tblMasterEntities = new HashSet<tblMasterEntity>();

        this.tblMilestones = new HashSet<tblMilestone>();

        this.tblPackageSCurves = new HashSet<tblPackageSCurve>();

        this.tblPackageValues = new HashSet<tblPackageValue>();

        this.tblPkgChngLvls = new HashSet<tblPkgChngLvl>();

        this.tblSCPkgChngLvls = new HashSet<tblSCPkgChngLvl>();

        this.tblPMCReportDetails = new HashSet<tblPMCReportDetail>();

        this.tblProcPkgMaterials = new HashSet<tblProcPkgMaterial>();

        this.tblReportPeriodMs = new HashSet<tblReportPeriodM>();

        this.tblResources = new HashSet<tblResource>();

        this.tblRFIUsers = new HashSet<tblRFIUser>();

        this.tblScActivityDetails = new HashSet<tblScActivityDetail>();

        this.tblScChainageUpdates = new HashSet<tblScChainageUpdate>();

        this.tblScCsDetails = new HashSet<tblScCsDetail>();

        this.tblSCPkgCrossSections = new HashSet<tblSCPkgCrossSection>();

        this.tblSections = new HashSet<tblSection>();

        this.tblStripPkgActs = new HashSet<tblStripPkgAct>();

    }


    public int PackageId { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public string PackageCode { get; set; }

    public string PackageName { get; set; }

    public string PackageShortName { get; set; }

    public string Description { get; set; }

    public string Client { get; set; }

    public string Contractor { get; set; }

    public string PMC { get; set; }

    public string PCPM { get; set; }

    public System.DateTime PackageStart { get; set; }

    public System.DateTime PackageFinish { get; set; }

    public Nullable<System.DateTime> ForecastComplDate { get; set; }

    public Nullable<double> PackageValue { get; set; }

    public Nullable<double> RevisedPackageValue { get; set; }

    public Nullable<double> CompletedValue { get; set; }

    public Nullable<double> BalanceValue { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public Nullable<double> TotalKmLength { get; set; }

    public Nullable<int> Duration { get; set; }

    public Nullable<int> EoTgranted { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsSubscribed { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCashFlow> tblCashFlows { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblInvoice> tblInvoices { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblKPIPlanActual> tblKPIPlanActuals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMasterEntity> tblMasterEntities { get; set; }

    public virtual tblMasterProject tblMasterProject { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMilestone> tblMilestones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPackageSCurve> tblPackageSCurves { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPackageValue> tblPackageValues { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPkgChngLvl> tblPkgChngLvls { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSCPkgChngLvl> tblSCPkgChngLvls { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPMCReportDetail> tblPMCReportDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblProcPkgMaterial> tblProcPkgMaterials { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblReportPeriodM> tblReportPeriodMs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblResource> tblResources { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIUser> tblRFIUsers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblScActivityDetail> tblScActivityDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblScChainageUpdate> tblScChainageUpdates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblScCsDetail> tblScCsDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSCPkgCrossSection> tblSCPkgCrossSections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblSection> tblSections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblStripPkgAct> tblStripPkgActs { get; set; }

}

}
