
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblpost
{

    public int postId { get; set; }

    public string title { get; set; }

    public string imageUrl { get; set; }

    public string content { get; set; }

    public Nullable<int> newColupdated { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
