
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblPackageValue
{

    public int AutoId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> InvoiceSubmitted { get; set; }

    public Nullable<decimal> TotalInvoicedAmount { get; set; }

    public Nullable<System.DateTime> LatestInvoiceDate { get; set; }

    public Nullable<decimal> LatestInvoiceAmount { get; set; }

    public Nullable<int> CertifiedInvoices { get; set; }

    public Nullable<decimal> CertifiedInvoiceAmount { get; set; }

    public Nullable<decimal> PendingAmount { get; set; }

    public Nullable<decimal> PaidInvoiceAmount { get; set; }

    public Nullable<decimal> BalancePaymentDue { get; set; }

    public Nullable<decimal> OriginalContractValue { get; set; }

    public Nullable<decimal> ProvisionalSum { get; set; }

    public Nullable<decimal> TotalContractValue { get; set; }

    public Nullable<int> ApprovedVariations { get; set; }

    public Nullable<decimal> ApprovedVariationValue { get; set; }

    public Nullable<decimal> RevisedContractValue { get; set; }

    public Nullable<int> ProposedVariations { get; set; }

    public Nullable<decimal> ProposedVariationValue { get; set; }



    public virtual tblPackage tblPackage { get; set; }

}

}
