
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblProjectType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblProjectType()
    {

        this.tblMasterProjects = new HashSet<tblMasterProject>();

    }


    public int ProjectTypeId { get; set; }

    public string ProjectTypeCode { get; set; }

    public string ProjectTypeName { get; set; }

    public Nullable<bool> IsDelete { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMasterProject> tblMasterProjects { get; set; }

}

}
