
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblProcPkgMaterial
{

    public int PkgMatId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> MaterialId { get; set; }

    public Nullable<decimal> RatePerUnit { get; set; }

    public Nullable<double> OriginalQty { get; set; }

    public string Unit { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    public virtual tblPackage tblPackage { get; set; }

    public virtual tblProcMaterial tblProcMaterial { get; set; }

}

}
