
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblPkgMatTransaction
{

    public int PkgMatTranId { get; set; }

    public Nullable<int> PkgMatId { get; set; }

    public Nullable<System.DateTime> TransDate { get; set; }

    public Nullable<double> RevisedQty { get; set; }

    public Nullable<double> OrderedQty { get; set; }

    public Nullable<double> DeliveredQty { get; set; }

    public string SupplierName { get; set; }

    public string PORef { get; set; }

    public Nullable<System.DateTime> TargetDate { get; set; }

    public string Remark { get; set; }

    public Nullable<int> AttachmentId { get; set; }



    public virtual tblAttachment tblAttachment { get; set; }

}

}
