
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFI
{

    public int ID { get; set; }

    public Nullable<System.DateTime> SubDate { get; set; }

    public Nullable<int> WorkGroupID { get; set; }

    public string RFIID { get; set; }

    public string LayerNo { get; set; }

    public Nullable<int> ActivityID { get; set; }

    public Nullable<int> Location { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public Nullable<int> EntityID { get; set; }

    public string OtherLocation { get; set; }

    public Nullable<int> WorksideID { get; set; }

    public string Remark { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> AddedBy { get; set; }



    public virtual tblWorkSide tblWorkSide { get; set; }

}

}
