
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblResource
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblResource()
    {

        this.tblKPIPlanActuals = new HashSet<tblKPIPlanActual>();

    }


    public int ResourceId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string ResourceName { get; set; }

    public string ResourceUnit { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblKPIPlanActual> tblKPIPlanActuals { get; set; }

    public virtual tblPackage tblPackage { get; set; }

}

}
