
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIPicture
{

    public int RFIPicId { get; set; }

    public Nullable<int> RFIRevId { get; set; }

    public string Picture { get; set; }

    public string Remarks { get; set; }

    public string PicPath { get; set; }

    public Nullable<int> AddedById { get; set; }

    public Nullable<System.DateTime> AddedOn { get; set; }

    public string AddedLocation { get; set; }

    public string InspStatus { get; set; }



    public virtual tblRFIRevision tblRFIRevision { get; set; }

    public virtual tblRFIUser tblRFIUser { get; set; }

}

}
