
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIDummy
{

    public int RFIId { get; set; }

    public int PkgId { get; set; }

    public Nullable<int> WorkGroupId { get; set; }

    public string RFICode { get; set; }

    public Nullable<int> LayerNo { get; set; }

    public Nullable<int> RFIActivityId { get; set; }

    public string LocationType { get; set; }

    public Nullable<double> StartChainge { get; set; }

    public Nullable<double> EndChainage { get; set; }

    public string Entity { get; set; }

    public string OtherWorkLocation { get; set; }

    public string WorkSide { get; set; }

    public string RFIStatus { get; set; }

    public Nullable<System.DateTime> RFIOpenDate { get; set; }

    public Nullable<System.DateTime> RFICloseDate { get; set; }

    public string WorkDescription { get; set; }

    public Nullable<double> ApprovedStartChainage { get; set; }

    public Nullable<double> ApprovedFinishChainage { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string RFINo { get; set; }

    public Nullable<System.DateTime> RecivedDatee { get; set; }

    public Nullable<System.DateTime> DateOfInspection { get; set; }

    public Nullable<System.DateTime> InspectionOn { get; set; }

    public string BOQItemNo { get; set; }

    public string ResultOfInspection { get; set; }

}

}
