
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIActivity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblRFIActivity()
    {

        this.tblRFIActivityBOQs = new HashSet<tblRFIActivityBOQ>();

        this.tblRFIMains = new HashSet<tblRFIMain>();

    }


    public int RFIActId { get; set; }

    public Nullable<int> ConsActId { get; set; }

    public Nullable<int> WorkGroupId { get; set; }

    public string RFIActName { get; set; }

    public string Unit { get; set; }

    public Nullable<bool> isDeleted { get; set; }



    public virtual tblConsActivity tblConsActivity { get; set; }

    public virtual tblWorkGroup tblWorkGroup { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIActivityBOQ> tblRFIActivityBOQs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIMain> tblRFIMains { get; set; }

}

}
