
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFITimelineActivity
{

    public int RFITimelineActID { get; set; }

    public string TimelineActText { get; set; }

    public string StatusClass { get; set; }

    public Nullable<System.DateTime> TimelineActDate { get; set; }

    public int RFIId { get; set; }

    public string AttachmentType { get; set; }

    public string AttachAutoId { get; set; }

}

}
