
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIEnclosure
{

    public int RFIEnclId { get; set; }

    public Nullable<int> RFIId { get; set; }

    public Nullable<int> EnclId { get; set; }

    public string EnclAttach { get; set; }

    public string EnclAttachPath { get; set; }

    public string Note { get; set; }



    public virtual tblEnclosure tblEnclosure { get; set; }

    public virtual tblRFIMain tblRFIMain { get; set; }

}

}
