
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIRevision
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblRFIRevision()
    {

        this.tblRFINotifications = new HashSet<tblRFINotification>();

        this.tblRFIPictures = new HashSet<tblRFIPicture>();

    }


    public int RFIRevId { get; set; }

    public Nullable<int> RFIId { get; set; }

    public string Revision { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string CreatedLocation { get; set; }

    public Nullable<int> AssignedTo { get; set; }

    public Nullable<int> AcceptedBy { get; set; }

    public Nullable<System.DateTime> AcceptedDate { get; set; }

    public Nullable<System.DateTime> InspDate { get; set; }

    public string InspBy { get; set; }

    public Nullable<int> InspId { get; set; }

    public string InspStatus { get; set; }

    public string Note { get; set; }

    public string ContrComment { get; set; }



    public virtual tblInspectionStatu tblInspectionStatu { get; set; }

    public virtual tblRFIMain tblRFIMain { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFINotification> tblRFINotifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIPicture> tblRFIPictures { get; set; }

}

}
