
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIActivityBOQ
{

    public int RFIActBOQId { get; set; }

    public Nullable<int> RFIActId { get; set; }

    public Nullable<int> RFIBOQId { get; set; }

    public string RFIBOQCode { get; set; }

    public Nullable<bool> IsDelete { get; set; }



    public virtual tblBOQMaster tblBOQMaster { get; set; }

    public virtual tblRFIActivity tblRFIActivity { get; set; }

}

}
