
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFIUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblRFIUser()
    {

        this.tblRFIPictures = new HashSet<tblRFIPicture>();

    }


    public int RFIUserId { get; set; }

    public Nullable<int> PackgeId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public string Organisation { get; set; }

    public Nullable<int> DesignationId { get; set; }

    public string Password { get; set; }

    public Nullable<int> ReportingTo { get; set; }

    public string DeviceId { get; set; }

    public string ProfilePic { get; set; }



    public virtual tblPackage tblPackage { get; set; }

    public virtual tblRFIDesignation tblRFIDesignation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIPicture> tblRFIPictures { get; set; }

}

}
