
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblRFINotification
{

    public int RFINotifyId { get; set; }

    public Nullable<int> RFIRevId { get; set; }

    public string Title { get; set; }

    public string Notification { get; set; }

    public Nullable<int> SentToId { get; set; }

    public Nullable<System.DateTime> SentOn { get; set; }

    public Nullable<System.DateTime> AcceptedOn { get; set; }



    public virtual tblRFIRevision tblRFIRevision { get; set; }

}

}
