
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblResidentEnggDetail
{

    public int WId { get; set; }

    public Nullable<int> AutoId { get; set; }

    public string ResidentEngineerName { get; set; }

    public string ResidentEngineerName2 { get; set; }

    public string ReWhatsAppNum { get; set; }

    public string Re2WhatsAppNum { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
