
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblSchedule
{

    public int ScheduleId { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<int> ModuleId { get; set; }

    public Nullable<int> TimeslotId { get; set; }

    public Nullable<bool> IsDelete { get; set; }

}

}
