
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblScChainageUpdate
{

    public int Id { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<System.DateTime> DataDate { get; set; }

    public Nullable<int> ActivityId { get; set; }

    public Nullable<double> StartChainage { get; set; }

    public Nullable<double> EndChainage { get; set; }

    public string Status { get; set; }



    public virtual tblPackage tblPackage { get; set; }

}

}
