
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblSystemResolutionDetail
{

    public int SysId { get; set; }

    public string UserName { get; set; }

    public string SystemName { get; set; }

    public string Resolution { get; set; }

    public string BrowserDetails { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
