
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblSCPkgChngLvl
{

    public int ID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string Chainage { get; set; }

    public Nullable<double> OGL { get; set; }

    public Nullable<double> FRL { get; set; }

    public Nullable<int> CsID { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }



    public virtual tblPackage tblPackage { get; set; }

    public virtual tblSCPkgChngLvl tblSCPkgChngLvl1 { get; set; }

    public virtual tblSCPkgChngLvl tblSCPkgChngLvl2 { get; set; }

}

}
