
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblScActivityDetail
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblScActivityDetail()
    {

        this.tblScCsDetails = new HashSet<tblScCsDetail>();

    }


    public int ScActID { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string ScActName { get; set; }

    public string PlotColour { get; set; }

    public Nullable<double> PlotThk { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tblPackage tblPackage { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblScCsDetail> tblScCsDetails { get; set; }

}

}
