
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblTicket
{

    public int TicketId { get; set; }

    public string TicketNo { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string Issue { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public Nullable<int> AddedBy { get; set; }

    public Nullable<System.DateTime> AddedOn { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> AttachmentId { get; set; }

    public string Comment { get; set; }

}

}
