
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblTargetSection
{

    public int TargetSectionId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public Nullable<int> SectionId { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> AddedOn { get; set; }

    public Nullable<int> AddedBy { get; set; }

}

}
