
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserLog
{

    public int LogID { get; set; }

    public int UserID { get; set; }

    public int PackageID { get; set; }

    public string IPAddress { get; set; }

    public string MACAddress { get; set; }

    public string FormName { get; set; }

    public string ActionName { get; set; }

    public string UpdatedValue { get; set; }

    public Nullable<System.DateTime> AccessedOn { get; set; }

}

}
