
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblUserPushNotifyId
{

    public int AutoId { get; set; }

    public Nullable<int> UserId { get; set; }

    public string UserType { get; set; }

    public string PushType { get; set; }

    public string PlayerId { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

}

}
