
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class tblWorkGroup
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblWorkGroup()
    {

        this.tblRFIActivities = new HashSet<tblRFIActivity>();

        this.tblRFIMains = new HashSet<tblRFIMain>();

    }


    public int WorkGrId { get; set; }

    public Nullable<int> DispId { get; set; }

    public string WorkGrName { get; set; }

    public string WorkGrPrefix { get; set; }



    public virtual tblDiscipline tblDiscipline { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIActivity> tblRFIActivities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblRFIMain> tblRFIMains { get; set; }

}

}
