
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class UserDetailsWithRole
{

    public int UserId { get; set; }

    public string Name { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string EmailId { get; set; }

    public string MobileNo { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<int> RoleTableId { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public string RoleName { get; set; }

    public string TableName { get; set; }

    public string TableDataName { get; set; }

    public string TableDataCode { get; set; }

    public string RoleCode { get; set; }

    public string FCMToken { get; set; }

    public string IosUserId { get; set; }

    public Nullable<int> Discipline { get; set; }

    public string PackageList { get; set; }

}

}
