
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewRfiActivity
{

    public int RFIActId { get; set; }

    public Nullable<int> ConsActId { get; set; }

    public Nullable<int> WorkGroupId { get; set; }

    public string RFIActName { get; set; }

    public string Unit { get; set; }

    public string WorkGrName { get; set; }

    public string ActivityName { get; set; }

    public Nullable<bool> isDeleted { get; set; }

}

}
