
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewPackageStatusReport
{

    public int PackageId { get; set; }

    public string PackageCode { get; set; }

    public string PackageShortName { get; set; }

    public string PackageName { get; set; }

    public string EDName { get; set; }

    public string CPMCode { get; set; }

    public string CPM { get; set; }

    public Nullable<int> SectionCount { get; set; }

    public Nullable<int> EntityCount { get; set; }

    public Nullable<int> EnggDwgCount { get; set; }

    public Nullable<int> MaterialAssignedCount { get; set; }

    public Nullable<int> MaterialDataUpdatedCount { get; set; }

    public Nullable<int> ConActCount { get; set; }

    public Nullable<int> ConActDataUpdateCount { get; set; }

    public Nullable<int> InvoiceCount { get; set; }

    public string Contractor { get; set; }

}

}
