
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ViewRFIUsersDetail
{

    public int RFIUserId { get; set; }

    public string FullName { get; set; }

    public string Mobile { get; set; }

    public string Email { get; set; }

    public string Organisation { get; set; }

    public Nullable<int> PackgeId { get; set; }

    public string PackageName { get; set; }

    public string Designation { get; set; }

    public Nullable<int> DesignationId { get; set; }

    public string Password { get; set; }

    public string ReportingToUser { get; set; }

}

}
