
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ViewRFIPDFDetail
{

    public int RFIId { get; set; }

    public int PkgId { get; set; }

    public string PackageName { get; set; }

    public string Description { get; set; }

    public string PMC { get; set; }

    public string Contractor { get; set; }

    public string Requestedby { get; set; }

    public string Client { get; set; }

    public string ProjectName { get; set; }

    public string BOQCode { get; set; }

    public string RFICode { get; set; }

    public string PrevRFICode { get; set; }

    public string WorkSide { get; set; }

    public string LocationType { get; set; }

    public Nullable<double> StartChainge { get; set; }

    public Nullable<double> EndChainage { get; set; }

    public string OtherWorkLocation { get; set; }

    public string RFIActName { get; set; }

    public Nullable<int> LayerNo { get; set; }

    public string RFIStatus { get; set; }

    public string WorkGrName { get; set; }

    public string Entity { get; set; }

    public string EntityName { get; set; }

    public Nullable<int> AssignedTo { get; set; }

    public Nullable<int> WorkGroupId { get; set; }

    public Nullable<int> RFIActivityId { get; set; }

    public Nullable<System.DateTime> RFIOpenDate { get; set; }

    public int RFIRevId { get; set; }

    public string AssignedToName { get; set; }

    public Nullable<System.DateTime> InspDate { get; set; }

    public Nullable<int> InspId { get; set; }

    public string InspStatus { get; set; }

    public string note { get; set; }

    public string Revision { get; set; }

    public Nullable<System.DateTime> AcceptedDate { get; set; }

    public Nullable<System.DateTime> DateOfSubmission { get; set; }

    public string WorkDescription { get; set; }

}

}
