
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewAllRisk
{

    public string RiskCode { get; set; }

    public string RiskType { get; set; }

    public string RiskCategory { get; set; }

    public Nullable<int> RiskPrimaryCategoryId { get; set; }

    public Nullable<int> RiskSecondaryCategoryId { get; set; }

    public Nullable<int> RiskTertiaryCategoryId { get; set; }

    public Nullable<int> RiskOwnerId { get; set; }

    public int RiskPriorityId { get; set; }

    public string RiskStatus { get; set; }

    public string RiskTitle { get; set; }

    public Nullable<System.DateTime> RiskTargetDate { get; set; }

    public Nullable<System.DateTime> RiskActualClosureDate { get; set; }

    public string RiskCause { get; set; }

    public string RiskDetail { get; set; }

    public string RiskEffect { get; set; }

    public Nullable<int> RiskCostImpact { get; set; }

    public string RiskCostImpactValue { get; set; }

    public string RiskScheduleImpactValue { get; set; }

    public Nullable<int> RiskScheduleImpact { get; set; }

    public Nullable<int> RiskPerformanceImpact { get; set; }

    public string RiskPerformanceImpactValue { get; set; }

    public Nullable<int> RiskSeverity { get; set; }

    public string RiskPriorityValue { get; set; }

    public string RiskContingencyTrigger { get; set; }

    public string RiskContingencyPlan { get; set; }

    public string RiskActionPlan { get; set; }

    public Nullable<bool> isPrivate { get; set; }

    public Nullable<bool> isClosed { get; set; }

    public Nullable<bool> isDeleted { get; set; }

    public Nullable<decimal> RiskBudget { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public int RiskId { get; set; }

    public int UserId { get; set; }

    public string RiskOwner { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public int ProjectId { get; set; }

}

}
