
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ViewSCurve
{

    public Nullable<int> PackageId { get; set; }

    public Nullable<System.DateTime> RPFinish { get; set; }

    public string RPName { get; set; }

    public Nullable<double> Actual { get; set; }

    public Nullable<double> PlanEarly { get; set; }

    public Nullable<double> PlanLate { get; set; }

    public Nullable<double> CumActual { get; set; }

    public Nullable<double> CumPlanEarly { get; set; }

}

}
