
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewUserNotificationMsg
{

    public int NotificationId { get; set; }

    public Nullable<int> SenderId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public Nullable<int> ReceiverId { get; set; }

    public Nullable<bool> isDelivered { get; set; }

    public Nullable<System.DateTime> SentOn { get; set; }

    public Nullable<System.DateTime> DeliveredOn { get; set; }

    public string Name { get; set; }

    public string UserName { get; set; }

    public string EmailId { get; set; }

    public string MobileNo { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<int> RoleTableId { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string CompanyName { get; set; }

    public string FCMToken { get; set; }

    public string IosUserId { get; set; }

    public string UserToken { get; set; }

    public string WhatsAppNo { get; set; }

}

}
