
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewUserNotify
{

    public int UserId { get; set; }

    public string Name { get; set; }

    public string EmailId { get; set; }

    public string MobileNo { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<int> RoleTableId { get; set; }

    public string FCMToken { get; set; }

    public string WhatsappNo { get; set; }

    public string IosUserId { get; set; }

    public string UserToken { get; set; }

}

}
