
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class viewStripChartSection
{

    public int SectionID { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string SectionName { get; set; }

    public string SectionCode { get; set; }

    public Nullable<double> StartChainage { get; set; }

    public Nullable<double> EndChainage { get; set; }

}

}
