
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ViewIssueRegister
{

    public int Id { get; set; }

    public string IssueRegNo { get; set; }

    public Nullable<int> PackageId { get; set; }

    public string IssueDescription { get; set; }

    public Nullable<int> DisciplineId { get; set; }

    public string StartChainage { get; set; }

    public string EndChainage { get; set; }

    public string otherLocation { get; set; }

    public Nullable<int> EntityId { get; set; }

    public Nullable<int> Location { get; set; }

    public Nullable<System.DateTime> IssueDate { get; set; }

    public string Attachment { get; set; }

    public string AttachmentPath { get; set; }

    public Nullable<bool> IsDelete { get; set; }

    public string Expr3 { get; set; }

    public int Expr1 { get; set; }

    public Nullable<int> SectionID { get; set; }

    public Nullable<int> Expr2 { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public string EntityCode { get; set; }

    public string EntityName { get; set; }

    public string EntityType { get; set; }

    public string Lat { get; set; }

    public string Long { get; set; }

    public string Expr14 { get; set; }

    public string Expr16 { get; set; }

    public Nullable<bool> Expr17 { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public Nullable<bool> Expr4 { get; set; }

    public string Expr5 { get; set; }

    public string Expr6 { get; set; }

    public Nullable<System.DateTime> Expr7 { get; set; }

    public Nullable<int> Expr8 { get; set; }

    public Nullable<int> Expr9 { get; set; }

    public string Expr10 { get; set; }

    public string Expr11 { get; set; }

    public string Expr12 { get; set; }

    public int Expr13 { get; set; }

    public string Expr15 { get; set; }

    public int Expr22 { get; set; }

    public string PackageCode { get; set; }

    public string PackageName { get; set; }

    public string PackageShortName { get; set; }

}

}
