
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RVNLMIS.DAC
{

using System;
    using System.Collections.Generic;
    
public partial class ViewCashFlow
{

    public Nullable<int> PackageId { get; set; }

    public string RPName { get; set; }

    public Nullable<System.DateTime> RPFinish { get; set; }

    public Nullable<System.DateTime> RPStart { get; set; }

    public Nullable<decimal> InvoiceAmount { get; set; }

    public Nullable<decimal> CertifiedAmount { get; set; }

    public Nullable<decimal> PaidAmount { get; set; }

    public Nullable<decimal> CumPaidAmount { get; set; }

    public Nullable<decimal> CumInvoiceAmount { get; set; }

    public Nullable<decimal> CumCertifiedAmount { get; set; }

}

}
